### ISSUE TITLE
Change server URL 

### ISSUE THREAD

**Issue by herrfrei** [evilbunny2008/weeWxWeatherApp#5]
How can I change the URL of my weewx server without deleting all data of the app? I moved weewx from one computer to another and now have problems to connect to the new web server.

**Comment by evilbunny2008** [comment]
To view the settings and make changes you just need to open the settings panel by swiping from the very edge of the left side of the screen and swipe to the right. The app doesn't store very much data, it's fed summary data from weeWX

**Comment by virtadpt** [comment]
> To view the settings and make changes you just need to open the settings panel by swiping from the very edge of the left side of the screen and swipe to the right.

That would be worth adding to the docs, I think.  Or a dedicated "tap the gears to open the settings" icon.

**Comment by evilbunny2008** [comment]
I thought swiping to bring up the settings panel was common knowledge.

**Comment by virtadpt** [comment]
'fraid not.  I found out about this app yesterday and was debugging my settings because I kept getting "weewx host not found" errors even though it was a typo in the radar maps line of my inigo-settings.txt file.  I had Argus index the bug tracker on this account and found this ticket because I couldn't figure out how to open the settings panel (in truth, I was afraid that there wasn't one and didn't feel like uninstalling and SD Maiding my phone just so that I could change the settings).  The standard "swipe up" didn't do anything I needed, and "swipe down to reload" didn't help.

Maybe it's just me (probably is) but this is the first app I've seen that doesn't have a settings gear.  Swiping left to right to open a pane makes sense in hindsight, but I don't think I would have thought to try it before Argus was done indexing everything in here.

**Comment by evilbunny2008** [comment]
> Maybe it's just me (probably is) but this is the first app I've seen that doesn't have a settings gear.

I tried to maximise screen space, I'll add a note to the GitHub/wiki to clarify.

>  "swipe down to reload" didn't help.

That's to forcibly refresh data/weather images/forecasts from the relevant servers once configured.

**Comment by virtadpt** [comment]
> That's to forcibly refresh data/weather images/forecasts from the relevant servers once configured.

I know.  I tried it in the hope of forcing an error that would pop the configuration window back up.

**Comment by evilbunny2008** [comment]
> I know. I tried it in the hope of forcing an error that would pop the configuration window back up.

The settings are cached and only save if there is no error.
